# Generated by Django 4.2 on 2024-05-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="company_name",
            field=models.CharField(blank=True, default="a", max_length=200, null=True),
        ),
    ]
