# Generated by Django 4.2 on 2024-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0002_customuser_phone_alter_applicant_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
