# Generated by Django 4.2 on 2024-05-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0002_applicant_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="business_email",
            field=models.CharField(blank=True, default="a", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="skills",
            field=models.CharField(blank=True, default="a", max_length=200, null=True),
        ),
    ]
