# Generated by Django 4.2 on 2024-05-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0003_applicant_business_email_applicant_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="business_email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="skills",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
