# Generated by Django 4.2.11 on 2024-05-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_applicant_business_email_applicant_company_name_and_more'),
        ('UserApp', '0004_alter_applicant_business_email_and_more'),
    ]

    operations = [
    ]
