# Generated by Django 4.2.11 on 2024-05-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_merge_20240508_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
