# Generated by Django 4.2.11 on 2024-05-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_rename_zip_applicant_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='zip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
