# Generated by Django 4.2.11 on 2024-05-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_remove_applicant_zip_code_applicant_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
