# Generated by Django 5.0.4 on 2024-05-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0009_rename_company_description_recruiter_about_company_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruiter",
            old_name="about_company",
            new_name="company_description",
        ),
        migrations.RenameField(
            model_name="recruiter",
            old_name="website",
            new_name="company_website",
        ),
        migrations.RemoveField(
            model_name="recruiter",
            name="address",
        ),
        migrations.RemoveField(
            model_name="recruiter",
            name="category",
        ),
        migrations.RemoveField(
            model_name="recruiter",
            name="city",
        ),
        migrations.RemoveField(
            model_name="recruiter",
            name="company_size",
        ),
        migrations.RemoveField(
            model_name="recruiter",
            name="country",
        ),
        migrations.RemoveField(
            model_name="recruiter",
            name="founded_date",
        ),
        migrations.RemoveField(
            model_name="recruiter",
            name="recruiter_name",
        ),
        migrations.RemoveField(
            model_name="recruiter",
            name="social_media",
        ),
        migrations.RemoveField(
            model_name="recruiter",
            name="state",
        ),
        migrations.RemoveField(
            model_name="recruiter",
            name="zip_code",
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="company_name",
            field=models.CharField(max_length=200),
        ),
    ]
