# Generated by Django 4.2 on 2024-05-13 15:29

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('Company', models.CharField(blank=True, max_length=200, null=True)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UserApp.applicant')),
            ],
            options={
                'unique_together': {('applicant', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('Academy', models.CharField(blank=True, max_length=200, null=True)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UserApp.applicant')),
            ],
            options={
                'unique_together': {('applicant', 'title')},
            },
        ),
    ]
