# Generated by Django 5.0.4 on 2024-05-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0010_rename_about_company_recruiter_company_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="company_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
