# Generated by Django 4.2 on 2024-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_customuser_username_experience_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='endDate',
        ),
        migrations.AlterField(
            model_name='education',
            name='Academy',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='startDate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Company',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startDate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
