# Generated by Django 4.2 on 2024-05-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_education_enddate_experience_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.applicant'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.applicant'),
        ),
    ]
