# Generated by Django 4.2 on 2024-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_alter_education_applicant_alter_experience_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Academy',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Company',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
    ]
