# Generated by Django 4.2 on 2024-05-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_alter_education_academy_alter_experience_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together=set(),
        ),
    ]
