# Generated by Django 4.2 on 2024-05-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_alter_education_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('applicant', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('applicant', 'title')},
        ),
    ]
