# Generated by Django 5.0.4 on 2024-05-18 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("UserApp", "0014_alter_education_academy_alter_experience_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("job_id", models.IntegerField(blank=True, default=None, null=True)),
                ("title", models.CharField(default=None, max_length=100)),
                ("company_name", models.CharField(default=None, max_length=100)),
                ("status", models.CharField(default=None, max_length=100)),
                ("years_of_experience", models.IntegerField(default=None)),
                ("description", models.TextField(default=None)),
                ("category", models.CharField(default=None, max_length=100)),
                ("type", models.CharField(default=None, max_length=100)),
                ("salary", models.CharField(default=None, max_length=100)),
                (
                    "MinSalary",
                    models.DecimalField(decimal_places=2, default=None, max_digits=10),
                ),
                (
                    "MaxSalary",
                    models.DecimalField(decimal_places=2, default=None, max_digits=10),
                ),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("english_fluency", models.CharField(default=None, max_length=100)),
                ("experience", models.CharField(default=None, max_length=100)),
                ("address", models.CharField(default=None, max_length=200)),
                ("country", models.CharField(default=None, max_length=100)),
                ("city", models.CharField(default=None, max_length=100)),
                ("zip_code", models.CharField(default=None, max_length=10)),
                ("state", models.CharField(default=None, max_length=100)),
                (
                    "recruiter",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserApp.recruiter",
                    ),
                ),
            ],
            options={
                "unique_together": {("job_id", "recruiter")},
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apply_date", models.DateTimeField(auto_now_add=True)),
                ("cover_letter", models.TextField()),
                ("accepted", models.BooleanField(default=False)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserApp.applicant",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CareerApp.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SavedCandidate",
                        to="UserApp.applicant",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserApp.recruiter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_date", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to="UserApp.applicant",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CareerApp.job"
                    ),
                ),
            ],
            options={
                "unique_together": {("applicant", "job")},
            },
        ),
    ]
