# Generated by Django 4.2 on 2024-05-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("UserApp", "0001_initial"),
        ("CareerApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedjob",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_jobs",
                to="UserApp.applicant",
            ),
        ),
        migrations.AddField(
            model_name="savedjob",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CareerApp.job"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CareerApp.jobcategory"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="UserApp.recruiter",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="UserApp.applicant"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CareerApp.job"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedjob",
            unique_together={("applicant", "job")},
        ),
    ]
