# Generated by Django 5.0.4 on 2024-05-08 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CareerApp", "0002_initial"),
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="job",
            unique_together={("id", "recruiter")},
        ),
        migrations.AddField(
            model_name="job",
            name="MaxSalary",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name="job",
            name="MinSalary",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name="job",
            name="address",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name="job",
            name="city",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="country",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="job",
            name="english_fluency",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name="job",
            name="state",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="type",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="years_of_experience",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="job",
            name="zip_code",
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="recruiter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserApp.recruiter",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.RemoveField(
            model_name="job",
            name="posted_date",
        ),
    ]
