# Generated by Django 5.0.4 on 2024-05-08 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CareerApp", "0003_alter_job_unique_together_job_maxsalary_and_more"),
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="id",
            new_name="job_id",
        ),
        migrations.AlterUniqueTogether(
            name="job",
            unique_together={("job_id", "recruiter")},
        ),
    ]
