# Generated by Django 5.0.4 on 2024-05-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CareerApp", "0004_rename_id_job_job_id_alter_job_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
