# Generated by Django 4.2 on 2024-05-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_alter_education_applicant_alter_experience_applicant'),
        ('CareerApp', '0005_alter_job_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SavedCandidate', to='UserApp.applicant')),
                ('recruiter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UserApp.recruiter')),
            ],
        ),
    ]
