# Generated by Django 4.2.10 on 2024-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0015_alter_customuser_username"),
        ("CareerApp", "0006_savedcandidate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="job",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="job",
            name="id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="job",
            unique_together={("id", "recruiter")},
        ),
    ]
