# Generated by Django 4.2.10 on 2024-05-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CareerApp",
            "0007_alter_job_unique_together_job_id_alter_job_job_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.IntegerField(),
        ),
    ]
